export const displayProducts = {
    "1173673":{
        "goodId":1173673,
        "mgoodId":"961173673",
        "name":"測試-0821-顏色-一般",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001173/1173673/1173673_XL.jpg?t=768439088",
        "cvsType":6,
        "price":1900,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"1137",
                "subStyleId":"0",
                "inStock":10,
                "styleName":"紅",
                "subStyleName":"共同",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"1137",
                    "name":"紅",
                    "inStock":10,
                    "isDefault":true
                },
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":false
                        }
                    ],
                    "id":"1136",
                    "name":"黃",
                    "inStock":10,
                    "isDefault":false
                },
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":false
                        }
                    ],
                    "id":"1096",
                    "name":"金",
                    "inStock":10,
                    "isDefault":false
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1174349":{
        "goodId":1174349,
        "mgoodId":"961174349",
        "name":"測試-0915-顏色+款式(13)-超商",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001174/1174349/1174349_XL.jpg?t=768778401",
        "cvsType":6,
        "price":1250,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"1137",
                "subStyleId":"1049",
                "inStock":10,
                "styleName":"藍紫色",
                "subStyleName":"限定款",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"1049",
                            "name":"限定款",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"1137",
                    "name":"藍紫色",
                    "inStock":10,
                    "isDefault":true
                },
                {
                    "subStyle":[
                        {
                            "id":"1048",
                            "name":"彩蛋款",
                            "inStock":10,
                            "isDefault":false
                        }
                    ],
                    "id":"1136",
                    "name":"橘黃色",
                    "inStock":10,
                    "isDefault":false
                },
                {
                    "subStyle":[
                        {
                            "id":"1047",
                            "name":"宇宙款",
                            "inStock":10,
                            "isDefault":false
                        }
                    ],
                    "id":"1096",
                    "name":"白黑色",
                    "inStock":10,
                    "isDefault":false
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1174757":{
        "goodId":1174757,
        "mgoodId":"961174757",
        "name":"測試-0915-無規格(3)贈-一般",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001174/1174757/1174757_XL.jpg?t=768792809",
        "cvsType":6,
        "price":0,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"0",
                "subStyleId":"0",
                "inStock":10,
                "styleName":"共同",
                "subStyleName":"共同",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"0",
                    "name":"共同",
                    "inStock":10,
                    "isDefault":true
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1175130":{
        "goodId":1175130,
        "mgoodId":"961175130",
        "name":"Plusone-20180920-03-批次加分類-贈品",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001175/1175130/1175130_XL.jpg?t=770048895",
        "cvsType":6,
        "price":0,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"0",
                "subStyleId":"0",
                "inStock":10,
                "styleName":"共同",
                "subStyleName":"共同",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"0",
                    "name":"共同",
                    "inStock":10,
                    "isDefault":true
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1176093":{
        "goodId":1176093,
        "mgoodId":"961176093",
        "name":"KIT 主商品",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001176/1176093/1176093_XL.jpg?t=782165334",
        "cvsType":6,
        "price":10000,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"0",
                "subStyleId":"0",
                "inStock":10,
                "styleName":"共同",
                "subStyleName":"共同",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"0",
                    "name":"共同",
                    "inStock":10,
                    "isDefault":true
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "5005117":{
        "goodId":5005117,
        "mgoodId":"965005117",
        "name":"測試ECTV網路商品提報複製成ECTV商品-TV",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/005005/5005117/5005117_XL.jpg?t=718212183",
        "cvsType":0,
        "price":1200,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"1007",
                "subStyleId":"1203",
                "inStock":2,
                "styleName":"白色",
                "subStyleName":"L",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"1203",
                            "name":"L",
                            "inStock":2,
                            "isDefault":true
                        },
                        {
                            "id":"1205",
                            "name":"S",
                            "inStock":4,
                            "isDefault":false
                        }
                    ],
                    "id":"1007",
                    "name":"白色",
                    "inStock":6,
                    "isDefault":true
                },
                {
                    "subStyle":[
                        {
                            "id":"1204",
                            "name":"M",
                            "inStock":4,
                            "isDefault":false
                        },
                        {
                            "id":"1203",
                            "name":"L",
                            "inStock":4,
                            "isDefault":false
                        },
                        {
                            "id":"1205",
                            "name":"S",
                            "inStock":4,
                            "isDefault":false
                        }
                    ],
                    "id":"1008",
                    "name":"黑色",
                    "inStock":12,
                    "isDefault":false
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "5004172":{
        "goodId":5004172,
        "mgoodId":"965004172",
        "name":"測試商品規格",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/005004/5004172/5004172_XL.jpg?t=718211622",
        "cvsType":0,
        "price":350,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"0",
                "subStyleId":"8101",
                "inStock":2,
                "styleName":"共同",
                "subStyleName":"款1",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"8101",
                            "name":"款1",
                            "inStock":2,
                            "isDefault":true
                        },
                        {
                            "id":"8102",
                            "name":"款2",
                            "inStock":2,
                            "isDefault":false
                        }
                    ],
                    "id":"0",
                    "name":"共同",
                    "inStock":4,
                    "isDefault":true
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1173739":{
        "goodId":1173739,
        "mgoodId":"961173739",
        "name":"測試-0821-無規格(2)-一般",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001173/1173739/1173739_XL.jpg?t=768446402",
        "cvsType":0,
        "price":220,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"0",
                "subStyleId":"0",
                "inStock":10,
                "styleName":"共同",
                "subStyleName":"共同",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"0",
                    "name":"共同",
                    "inStock":10,
                    "isDefault":true
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "5004939":{
        "goodId":5004939,
        "mgoodId":"965004939",
        "name":"測試旅遊自訂規格",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/005004/5004939/5004939_XL.jpg?t=718212034",
        "cvsType":0,
        "price":13000,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"1019",
                "subStyleId":"1027",
                "inStock":10,
                "styleName":"5月",
                "subStyleName":"1日",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"1027",
                            "name":"1日",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"1019",
                    "name":"5月",
                    "inStock":10,
                    "isDefault":true
                },
                {
                    "subStyle":[
                        {
                            "id":"1002",
                            "name":"2日",
                            "inStock":10,
                            "isDefault":false
                        }
                    ],
                    "id":"1018",
                    "name":"5月",
                    "inStock":10,
                    "isDefault":false
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1173604":{
        "goodId":1173604,
        "mgoodId":"961173604",
        "name":"測試-0820-無規格-一般",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001173/1173604/1173604_XL.jpg?t=769146406",
        "cvsType":0,
        "price":170,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"0",
                "subStyleId":"0",
                "inStock":10,
                "styleName":"共同",
                "subStyleName":"共同",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"0",
                    "name":"共同",
                    "inStock":10,
                    "isDefault":true
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1174083":{
        "goodId":1174083,
        "mgoodId":"961174083",
        "name":"測試-0915-顏色+款式(2)-一般",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001174/1174083/1174083_XL.jpg?t=768755162",
        "cvsType":6,
        "price":2000,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"1137",
                "subStyleId":"1048",
                "inStock":10,
                "styleName":"紅",
                "subStyleName":"m",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"1048",
                            "name":"m",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"1137",
                    "name":"紅",
                    "inStock":10,
                    "isDefault":true
                },
                {
                    "subStyle":[
                        {
                            "id":"1198",
                            "name":"L",
                            "inStock":10,
                            "isDefault":false
                        }
                    ],
                    "id":"1136",
                    "name":"紫",
                    "inStock":10,
                    "isDefault":false
                },
                {
                    "subStyle":[
                        {
                            "id":"1047",
                            "name":"x",
                            "inStock":10,
                            "isDefault":false
                        }
                    ],
                    "id":"1096",
                    "name":"黃",
                    "inStock":10,
                    "isDefault":false
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1172856":{
        "goodId":1172856,
        "mgoodId":"961172856",
        "name":"測試專用_3H-快配商品%^*)(",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001172/1172856/1172856_XL.jpg?t=766284682",
        "cvsType":0,
        "price":1000,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"0",
                "subStyleId":"0",
                "inStock":10,
                "styleName":"共同",
                "subStyleName":"共同",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"0",
                    "name":"共同",
                    "inStock":10,
                    "isDefault":true
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1174062":{
        "goodId":1174062,
        "mgoodId":"961174062",
        "name":"測試-0915-無規格(1)-一般",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001174/1174062/1174062_XL.jpg?t=768754447",
        "cvsType":6,
        "price":1300,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"0",
                "subStyleId":"0",
                "inStock":10,
                "styleName":"共同",
                "subStyleName":"共同",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"0",
                    "name":"共同",
                    "inStock":10,
                    "isDefault":true
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1174572":{
        "goodId":1174572,
        "mgoodId":"961174572",
        "name":"測試-0915-無規格(3)任-超商",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001174/1174572/1174572_XL.jpg?t=769159500",
        "cvsType":6,
        "price":800,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"0",
                "subStyleId":"0",
                "inStock":10,
                "styleName":"共同",
                "subStyleName":"共同",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"0",
                    "name":"共同",
                    "inStock":10,
                    "isDefault":true
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1174571":{
        "goodId":1174571,
        "mgoodId":"961174571",
        "name":"測試-0915-無規格(4)任-超商",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001174/1174571/1174571_XL.jpg?t=769159488",
        "cvsType":6,
        "price":850,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"0",
                "subStyleId":"0",
                "inStock":10,
                "styleName":"共同",
                "subStyleName":"共同",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"0",
                    "name":"共同",
                    "inStock":10,
                    "isDefault":true
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1174597":{
        "goodId":1174597,
        "mgoodId":"961174597",
        "name":"測試-0915-款式(4)-超商",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001174/1174597/1174597_XL.jpg?t=769160092",
        "cvsType":6,
        "price":1900,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"0",
                "subStyleId":"1049",
                "inStock":10,
                "styleName":"共同",
                "subStyleName":"藍姆款",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"1049",
                            "name":"藍姆款",
                            "inStock":10,
                            "isDefault":true
                        },
                        {
                            "id":"1048",
                            "name":"檸檬款",
                            "inStock":10,
                            "isDefault":false
                        },
                        {
                            "id":"1047",
                            "name":"藍莓款",
                            "inStock":10,
                            "isDefault":false
                        }
                    ],
                    "id":"0",
                    "name":"共同",
                    "inStock":30,
                    "isDefault":true
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1172490":{
        "goodId":1172490,
        "mgoodId":"961172490",
        "name":"加-戴芬妮甜心鑽墜",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001172/1172490/1172490_XL.jpg?t=718900954",
        "cvsType":0,
        "price":4999,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"1096",
                "subStyleId":"1128",
                "inStock":10,
                "styleName":"白金",
                "subStyleName":"A",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"1128",
                            "name":"A",
                            "inStock":10,
                            "isDefault":true
                        },
                        {
                            "id":"1129",
                            "name":"B",
                            "inStock":10,
                            "isDefault":false
                        },
                        {
                            "id":"1130",
                            "name":"C",
                            "inStock":10,
                            "isDefault":false
                        }
                    ],
                    "id":"1096",
                    "name":"白金",
                    "inStock":30,
                    "isDefault":true
                },
                {
                    "subStyle":[
                        {
                            "id":"1128",
                            "name":"A",
                            "inStock":10,
                            "isDefault":false
                        },
                        {
                            "id":"1129",
                            "name":"B",
                            "inStock":10,
                            "isDefault":false
                        },
                        {
                            "id":"1130",
                            "name":"C",
                            "inStock":10,
                            "isDefault":false
                        }
                    ],
                    "id":"1301",
                    "name":"金色",
                    "inStock":30,
                    "isDefault":false
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1176012":{
        "goodId":1176012,
        "mgoodId":"961176012",
        "name":"測試用商品123456-駁回",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001176/1176012/1176012_XL.jpg?t=781498873",
        "cvsType":6,
        "price":1000,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"0",
                "subStyleId":"0",
                "inStock":10,
                "styleName":"共同",
                "subStyleName":"共同",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"0",
                    "name":"共同",
                    "inStock":10,
                    "isDefault":true
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1176804":{
        "goodId":1176804,
        "mgoodId":"961176804",
        "name":"【B.S.D.S冰山袋鼠】日系印花後背包-六色選擇",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001176/1176804/1176804_XL.jpg?t=786588689",
        "cvsType":0,
        "price":990,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"0",
                "subStyleId":"0",
                "inStock":5,
                "styleName":"共同",
                "subStyleName":"共同",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":5,
                            "isDefault":true
                        }
                    ],
                    "id":"0",
                    "name":"共同",
                    "inStock":5,
                    "isDefault":true
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1171636":{
        "goodId":1171636,
        "mgoodId":"961171636",
        "name":"加-測-加1",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001171/1171636/1171636_XL.jpg?t=718211378",
        "cvsType":0,
        "price":1000,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"0",
                "subStyleId":"0",
                "inStock":10,
                "styleName":"共同",
                "subStyleName":"共同",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"0",
                    "name":"共同",
                    "inStock":10,
                    "isDefault":true
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1171635":{
        "goodId":1171635,
        "mgoodId":"961171635",
        "name":"加-測-加2",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001171/1171635/1171635_XL.jpg?t=718211392",
        "cvsType":0,
        "price":1000,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"0",
                "subStyleId":"0",
                "inStock":10,
                "styleName":"共同",
                "subStyleName":"共同",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"0",
                    "name":"共同",
                    "inStock":10,
                    "isDefault":true
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1173963":{
        "goodId":1173963,
        "mgoodId":"961173963",
        "name":"刺蝟寶寶貼紙_超取_加價購_款式",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001173/1173963/1173963_XL.jpg?t=768686234",
        "cvsType":0,
        "price":24,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"0",
                "subStyleId":"1048",
                "inStock":10,
                "styleName":"共同",
                "subStyleName":"全家福",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"1048",
                            "name":"全家福",
                            "inStock":10,
                            "isDefault":true
                        },
                        {
                            "id":"1047",
                            "name":"刺蝟款",
                            "inStock":10,
                            "isDefault":false
                        }
                    ],
                    "id":"0",
                    "name":"共同",
                    "inStock":20,
                    "isDefault":true
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1174537":{
        "goodId":1174537,
        "mgoodId":"961174537",
        "name":"測試-0915-顏色+款式(3)加-超商",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001174/1174537/1174537_XL.jpg?t=768785042",
        "cvsType":6,
        "price":750,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"1137",
                "subStyleId":"1049",
                "inStock":10,
                "styleName":"藍紫色",
                "subStyleName":"限定款",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"1049",
                            "name":"限定款",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"1137",
                    "name":"藍紫色",
                    "inStock":10,
                    "isDefault":true
                },
                {
                    "subStyle":[
                        {
                            "id":"1048",
                            "name":"彩蛋款",
                            "inStock":10,
                            "isDefault":false
                        }
                    ],
                    "id":"1136",
                    "name":"橘黃色",
                    "inStock":10,
                    "isDefault":false
                },
                {
                    "subStyle":[
                        {
                            "id":"1047",
                            "name":"宇宙款",
                            "inStock":10,
                            "isDefault":false
                        }
                    ],
                    "id":"1096",
                    "name":"白黑色",
                    "inStock":10,
                    "isDefault":false
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1174538":{
        "goodId":1174538,
        "mgoodId":"961174538",
        "name":"測試-0915-顏色+款式(2)加-超商",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001174/1174538/1174538_XL.jpg?t=768785077",
        "cvsType":6,
        "price":700,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"1137",
                "subStyleId":"1049",
                "inStock":10,
                "styleName":"藍紫色",
                "subStyleName":"限定款",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"1049",
                            "name":"限定款",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"1137",
                    "name":"藍紫色",
                    "inStock":10,
                    "isDefault":true
                },
                {
                    "subStyle":[
                        {
                            "id":"1048",
                            "name":"彩蛋款",
                            "inStock":10,
                            "isDefault":false
                        }
                    ],
                    "id":"1136",
                    "name":"橘黃色",
                    "inStock":10,
                    "isDefault":false
                },
                {
                    "subStyle":[
                        {
                            "id":"1047",
                            "name":"宇宙款",
                            "inStock":10,
                            "isDefault":false
                        }
                    ],
                    "id":"1096",
                    "name":"白黑色",
                    "inStock":10,
                    "isDefault":false
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1174549":{
        "goodId":1174549,
        "mgoodId":"961174549",
        "name":"測試-0915-顏色(1)加-超商",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001174/1174549/1174549_XL.jpg?t=768785462",
        "cvsType":6,
        "price":400,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"1301",
                "subStyleId":"0",
                "inStock":10,
                "styleName":"金色",
                "subStyleName":"共同",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"1301",
                    "name":"金色",
                    "inStock":10,
                    "isDefault":true
                },
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":false
                        }
                    ],
                    "id":"1066",
                    "name":"灰色",
                    "inStock":10,
                    "isDefault":false
                },
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":false
                        }
                    ],
                    "id":"1316",
                    "name":"黑色",
                    "inStock":10,
                    "isDefault":false
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1174552":{
        "goodId":1174552,
        "mgoodId":"961174552",
        "name":"測試-0915-無規格(3)加-超商",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001174/1174552/1174552_XL.jpg?t=768785561",
        "cvsType":6,
        "price":800,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"0",
                "subStyleId":"0",
                "inStock":10,
                "styleName":"共同",
                "subStyleName":"共同",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"0",
                    "name":"共同",
                    "inStock":10,
                    "isDefault":true
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1174539":{
        "goodId":1174539,
        "mgoodId":"961174539",
        "name":"測試-0915-顏色+款式(1)加-超商",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001174/1174539/1174539_XL.jpg?t=768785112",
        "cvsType":6,
        "price":650,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"1137",
                "subStyleId":"1049",
                "inStock":10,
                "styleName":"藍紫色",
                "subStyleName":"限定款",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"1049",
                            "name":"限定款",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"1137",
                    "name":"藍紫色",
                    "inStock":10,
                    "isDefault":true
                },
                {
                    "subStyle":[
                        {
                            "id":"1048",
                            "name":"彩蛋款",
                            "inStock":10,
                            "isDefault":false
                        }
                    ],
                    "id":"1136",
                    "name":"橘黃色",
                    "inStock":10,
                    "isDefault":false
                },
                {
                    "subStyle":[
                        {
                            "id":"1047",
                            "name":"宇宙款",
                            "inStock":10,
                            "isDefault":false
                        }
                    ],
                    "id":"1096",
                    "name":"白黑色",
                    "inStock":10,
                    "isDefault":false
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1174543":{
        "goodId":1174543,
        "mgoodId":"961174543",
        "name":"測試-0915-款式(2)加-超商",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001174/1174543/1174543_XL.jpg?t=768785252",
        "cvsType":6,
        "price":900,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"0",
                "subStyleId":"1049",
                "inStock":10,
                "styleName":"共同",
                "subStyleName":"藍姆款",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"1049",
                            "name":"藍姆款",
                            "inStock":10,
                            "isDefault":true
                        },
                        {
                            "id":"1048",
                            "name":"檸檬款",
                            "inStock":10,
                            "isDefault":false
                        },
                        {
                            "id":"1047",
                            "name":"藍莓款",
                            "inStock":10,
                            "isDefault":false
                        }
                    ],
                    "id":"0",
                    "name":"共同",
                    "inStock":30,
                    "isDefault":true
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1174547":{
        "goodId":1174547,
        "mgoodId":"961174547",
        "name":"測試-0915-顏色(3)加-超商",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001174/1174547/1174547_XL.jpg?t=768785392",
        "cvsType":6,
        "price":400,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"1301",
                "subStyleId":"0",
                "inStock":10,
                "styleName":"金色",
                "subStyleName":"共同",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"1301",
                    "name":"金色",
                    "inStock":10,
                    "isDefault":true
                },
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":false
                        }
                    ],
                    "id":"1066",
                    "name":"灰色",
                    "inStock":10,
                    "isDefault":false
                },
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":false
                        }
                    ],
                    "id":"1316",
                    "name":"黑色",
                    "inStock":10,
                    "isDefault":false
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1174548":{
        "goodId":1174548,
        "mgoodId":"961174548",
        "name":"測試-0915-顏色(2)加-超商",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001174/1174548/1174548_XL.jpg?t=768785427",
        "cvsType":6,
        "price":400,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"1301",
                "subStyleId":"0",
                "inStock":10,
                "styleName":"金色",
                "subStyleName":"共同",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"1301",
                    "name":"金色",
                    "inStock":10,
                    "isDefault":true
                },
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":false
                        }
                    ],
                    "id":"1066",
                    "name":"灰色",
                    "inStock":10,
                    "isDefault":false
                },
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":false
                        }
                    ],
                    "id":"1316",
                    "name":"黑色",
                    "inStock":10,
                    "isDefault":false
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1173974":{
        "goodId":1173974,
        "mgoodId":"961173974",
        "name":"魔法手錶_超取_贈品_款式",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001173/1173974/1173974_XL.jpg?t=768686810",
        "cvsType":6,
        "price":0,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"0",
                "subStyleId":"1048",
                "inStock":10,
                "styleName":"共同",
                "subStyleName":"魔法款",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"1048",
                            "name":"魔法款",
                            "inStock":10,
                            "isDefault":true
                        },
                        {
                            "id":"1047",
                            "name":"魔力款",
                            "inStock":10,
                            "isDefault":false
                        }
                    ],
                    "id":"0",
                    "name":"共同",
                    "inStock":20,
                    "isDefault":true
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1172935":{
        "goodId":1172935,
        "mgoodId":"961172935",
        "name":"網路贈品提報測試-網贈",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001172/1172935/1172935_XL.jpg?t=777520815",
        "cvsType":6,
        "price":0,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"0",
                "subStyleId":"0",
                "inStock":10,
                "styleName":"共同",
                "subStyleName":"共同",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"0",
                    "name":"共同",
                    "inStock":10,
                    "isDefault":true
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1172944":{
        "goodId":1172944,
        "mgoodId":"961172944",
        "name":"測試網路贈品提報1214-有款式",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001172/1172944/1172944_XL.jpg?t=766634188",
        "cvsType":0,
        "price":0,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"1089",
                "subStyleId":"6862",
                "inStock":2,
                "styleName":"米色",
                "subStyleName":"s",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"6862",
                            "name":"s",
                            "inStock":2,
                            "isDefault":true
                        },
                        {
                            "id":"1047",
                            "name":"m",
                            "inStock":9,
                            "isDefault":false
                        }
                    ],
                    "id":"1089",
                    "name":"米色",
                    "inStock":11,
                    "isDefault":true
                },
                {
                    "subStyle":[
                        {
                            "id":"6862",
                            "name":"s",
                            "inStock":9,
                            "isDefault":false
                        },
                        {
                            "id":"1047",
                            "name":"m",
                            "inStock":9,
                            "isDefault":false
                        }
                    ],
                    "id":"1088",
                    "name":"卵石灰",
                    "inStock":18,
                    "isDefault":false
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1173944":{
        "goodId":1173944,
        "mgoodId":"961173944",
        "name":"咖啡檸檬片_一般_贈品_無規格",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001173/1173944/1173944_XL.jpg?t=768685140",
        "cvsType":0,
        "price":0,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"0",
                "subStyleId":"0",
                "inStock":10,
                "styleName":"共同",
                "subStyleName":"共同",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"0",
                    "name":"共同",
                    "inStock":10,
                    "isDefault":true
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1173945":{
        "goodId":1173945,
        "mgoodId":"961173945",
        "name":"造型糖果屋_一般_贈品_無規格",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001173/1173945/1173945_XL.jpg?t=768685175",
        "cvsType":0,
        "price":0,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"0",
                "subStyleId":"0",
                "inStock":10,
                "styleName":"共同",
                "subStyleName":"共同",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"0",
                    "name":"共同",
                    "inStock":10,
                    "isDefault":true
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1173946":{
        "goodId":1173946,
        "mgoodId":"961173946",
        "name":"黑熊抱枕_一般_贈品_顏色",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001173/1173946/1173946_XL.jpg?t=768685216",
        "cvsType":0,
        "price":0,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"1316",
                "subStyleId":"0",
                "inStock":10,
                "styleName":"黑色",
                "subStyleName":"共同",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"1316",
                    "name":"黑色",
                    "inStock":10,
                    "isDefault":true
                },
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":false
                        }
                    ],
                    "id":"1066",
                    "name":"灰色",
                    "inStock":10,
                    "isDefault":false
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1173947":{
        "goodId":1173947,
        "mgoodId":"961173947",
        "name":"電話遊戲套組_一般_贈品_顏色",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001173/1173947/1173947_XL.jpg?t=768685253",
        "cvsType":0,
        "price":0,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"1136",
                "subStyleId":"0",
                "inStock":10,
                "styleName":"blue",
                "subStyleName":"共同",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"1136",
                    "name":"blue",
                    "inStock":10,
                    "isDefault":true
                },
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":false
                        }
                    ],
                    "id":"1096",
                    "name":"red",
                    "inStock":10,
                    "isDefault":false
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1173948":{
        "goodId":1173948,
        "mgoodId":"961173948",
        "name":"飛天小女警抱枕_一般_贈品_款式",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001173/1173948/1173948_XL.jpg?t=768685292",
        "cvsType":0,
        "price":0,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"0",
                "subStyleId":"1049",
                "inStock":10,
                "styleName":"共同",
                "subStyleName":"泡泡款",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"1049",
                            "name":"泡泡款",
                            "inStock":10,
                            "isDefault":true
                        },
                        {
                            "id":"1048",
                            "name":"小毛款",
                            "inStock":10,
                            "isDefault":false
                        },
                        {
                            "id":"1047",
                            "name":"花花款",
                            "inStock":10,
                            "isDefault":false
                        }
                    ],
                    "id":"0",
                    "name":"共同",
                    "inStock":30,
                    "isDefault":true
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1173949":{
        "goodId":1173949,
        "mgoodId":"961173949",
        "name":"日本空運柚子_一般_贈品_款式",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001173/1173949/1173949_XL.jpg?t=768685394",
        "cvsType":0,
        "price":0,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"0",
                "subStyleId":"0",
                "inStock":10,
                "styleName":"共同",
                "subStyleName":"共同",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"0",
                    "name":"共同",
                    "inStock":10,
                    "isDefault":true
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1172972":{
        "goodId":1172972,
        "mgoodId":"961172972",
        "name":"加-墨攻-180114-005ydddy",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001172/1172972/1172972_XL.jpg?t=773362191",
        "cvsType":0,
        "price":800,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"0",
                "subStyleId":"0",
                "inStock":10,
                "styleName":"共同",
                "subStyleName":"共同",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"0",
                    "name":"共同",
                    "inStock":10,
                    "isDefault":true
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1173360":{
        "goodId":1173360,
        "mgoodId":"961173360",
        "name":"(滿額加價購專用)力麗馬告明池山莊海鮮大餐吃到飽",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001173/1173360/1173360_XL.jpg?t=767518537",
        "cvsType":0,
        "price":3380,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"0",
                "subStyleId":"0",
                "inStock":10,
                "styleName":"共同",
                "subStyleName":"共同",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"0",
                    "name":"共同",
                    "inStock":10,
                    "isDefault":true
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1173935":{
        "goodId":1173935,
        "mgoodId":"961173935",
        "name":"氣球冰淇淋_一般加價購_顏色",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001173/1173935/1173935_XL.jpg?t=768684626",
        "cvsType":0,
        "price":299,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"1136",
                "subStyleId":"0",
                "inStock":10,
                "styleName":"藍色汽球",
                "subStyleName":"共同",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"1136",
                    "name":"藍色汽球",
                    "inStock":10,
                    "isDefault":true
                },
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":false
                        }
                    ],
                    "id":"1096",
                    "name":"粉紅氣球",
                    "inStock":10,
                    "isDefault":false
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1173938":{
        "goodId":1173938,
        "mgoodId":"961173938",
        "name":"芒果爽_一般加價購_款式",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001173/1173938/1173938_XL.jpg?t=768684798",
        "cvsType":0,
        "price":188,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"0",
                "subStyleId":"1048",
                "inStock":10,
                "styleName":"共同",
                "subStyleName":"芒果口味",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"1048",
                            "name":"芒果口味",
                            "inStock":10,
                            "isDefault":true
                        },
                        {
                            "id":"1047",
                            "name":"香草口味",
                            "inStock":10,
                            "isDefault":false
                        }
                    ],
                    "id":"0",
                    "name":"共同",
                    "inStock":20,
                    "isDefault":true
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1173933":{
        "goodId":1173933,
        "mgoodId":"961173933",
        "name":"煙火餅乾_一般加價購_無規格",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001173/1173933/1173933_XL.jpg?t=768674918",
        "cvsType":0,
        "price":420,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"0",
                "subStyleId":"0",
                "inStock":10,
                "styleName":"共同",
                "subStyleName":"共同",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"0",
                    "name":"共同",
                    "inStock":10,
                    "isDefault":true
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1173936":{
        "goodId":1173936,
        "mgoodId":"961173936",
        "name":"火龍果炒冰組合_一般加價購_顏色",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001173/1173936/1173936_XL.jpg?t=768684700",
        "cvsType":0,
        "price":377,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"1136",
                "subStyleId":"0",
                "inStock":10,
                "styleName":"火龍果色",
                "subStyleName":"共同",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"1136",
                    "name":"火龍果色",
                    "inStock":10,
                    "isDefault":true
                },
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":false
                        }
                    ],
                    "id":"1096",
                    "name":"青木瓜色",
                    "inStock":10,
                    "isDefault":false
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1173943":{
        "goodId":1173943,
        "mgoodId":"961173943",
        "name":"可愛無尾熊_一般加價購_顏色+款式",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001173/1173943/1173943_XL.jpg?t=768685052",
        "cvsType":0,
        "price":299,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"1066",
                "subStyleId":"1048",
                "inStock":10,
                "styleName":"灰色",
                "subStyleName":"嬤嬤款",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"1048",
                            "name":"嬤嬤款",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"1066",
                    "name":"灰色",
                    "inStock":10,
                    "isDefault":true
                },
                {
                    "subStyle":[
                        {
                            "id":"1047",
                            "name":"弟弟款",
                            "inStock":10,
                            "isDefault":false
                        }
                    ],
                    "id":"1007",
                    "name":"白色",
                    "inStock":10,
                    "isDefault":false
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    },
    "1175380":{
        "goodId":1175380,
        "mgoodId":"961175380",
        "name":"加價購－一般",
        "imageUrl":"//cdn-lab.etzone.net/NXimg/001175/1175380/1175380_XL.jpg?t=775548754",
        "cvsType":0,
        "price":200,
        "styleInfo":{
            "defaultStyle":{
                "styleId":"0",
                "subStyleId":"0",
                "inStock":10,
                "styleName":"共同",
                "subStyleName":"共同",
                "quantity":null
            },
            "styleList":[
                {
                    "subStyle":[
                        {
                            "id":"0",
                            "name":"共同",
                            "inStock":10,
                            "isDefault":true
                        }
                    ],
                    "id":"0",
                    "name":"共同",
                    "inStock":10,
                    "isDefault":true
                }
            ],
            "maximumOfSinglePurchase":10
        },
        "canUseGiftCard":true,
        "canReturn":true,
        "isGreenPoint":false,
        "rewardGreenPoint":0
    }
}

export const basketProducts = {
    "0":{
        "groupId":"0",
        "groupKey":null,
        "groupType":null,
        "items":[
            {
                "itemId":"46ef78b1-3050-4d86-9bcb-4df083be7d79",
                "productUrl":"/i/1176012?Store=4416\u0026Cate=36625",
                "couponId":"",
                "basketId":0,
                "cateNames":[
                    "視聽家電",
                    "家用電視",
                    "BenQ 明基",
                    "42吋"
                ],
                "goodId":1176012,
                "cateId":36625,
                "amount":1,
                "colorId":"0",
                "styleId":"0",
                "gaCode":"mWeb_Home_HotRank_Product_全館_1176012_18",
                "parentSaleNo":null,
                "isJajago":false,
                "isGift":false,
                "isKit":false,
                "isKitItem":false,
                "giftNeedPickCount":0
            },
            {
                "itemId":"a095dc14-a142-42c1-b8bf-e1e1eed484b2",
                "productUrl":"/i/1176093?Store=4416\u0026Cate=46352",
                "couponId":"",
                "basketId":0,
                "cateNames":[
                    "視聽家電",
                    "坎蒂專區",
                    "測試隱藏分類",
                    "隱藏分類1aaaa"
                ],
                "goodId":1176093,
                "cateId":46352,
                "amount":1,
                "colorId":"0",
                "styleId":"0",
                "gaCode":"",
                "parentSaleNo":null,
                "isJajago":false,
                "isGift":false,
                "isKit":true,
                "isKitItem":false,
                "giftNeedPickCount":0
            },
            {
                "itemId":"acc1175f-ef10-4720-88f5-21fde8aaa4a0",
                "productUrl":"/i/5004172",
                "couponId":"",
                "basketId":0,
                "cateNames":[

                ],
                "goodId":5004172,
                "cateId":0,
                "amount":1,
                "colorId":"0",
                "styleId":"8101",
                "gaCode":"",
                "parentSaleNo":1176093,
                "isJajago":false,
                "isGift":false,
                "isKit":false,
                "isKitItem":true,
                "giftNeedPickCount":0
            },
            {
                "itemId":"9307a056-18cf-4729-b1a8-87b8fca9c4ca",
                "productUrl":"/i/5005117",
                "couponId":"",
                "basketId":0,
                "cateNames":[

                ],
                "goodId":5005117,
                "cateId":0,
                "amount":1,
                "colorId":"1007",
                "styleId":"1203",
                "gaCode":"",
                "parentSaleNo":1176093,
                "isJajago":false,
                "isGift":false,
                "isKit":false,
                "isKitItem":true,
                "giftNeedPickCount":0
            }
        ],
        "name":null,
        "link":null,
        "thresholdType":null,
        "thresholdValue":0
    },
    "Campaign_41308":{
        "groupId":"Campaign_41308",
        "groupKey":"41308",
        "groupType":"Campaign_GG",
        "items":[
            {
                "itemId":"d128e1e5-a98f-4a64-be7d-ce5bc40ca628",
                "productUrl":"/i/1173673?Store=2\u0026Cate=19357",
                "couponId":"",
                "basketId":0,
                "cateNames":[
                    "服飾鞋包",
                    "時尚女裝",
                    "款式特搜－裙 ｜ 褲",
                    "短裙"
                ],
                "goodId":1173673,
                "cateId":19357,
                "amount":1,
                "colorId":"1137",
                "styleId":"0",
                "gaCode":"mWeb_Home_HotRank_Product_全館_1173673_02",
                "parentSaleNo":null,
                "isJajago":false,
                "isGift":false,
                "isKit":false,
                "isKitItem":false,
                "giftNeedPickCount":0
            }
        ],
        "name":"滿額加價購",
        "link":"/p/41308",
        "thresholdType":"Price",
        "thresholdValue":100
    },
    "Campaign_40229":{
        "groupId":"Campaign_40229",
        "groupKey":"40229",
        "groupType":"Campaign_GG",
        "items":[
            {
                "itemId":"20f26e51-7aeb-4bef-8d87-912317ed7747",
                "productUrl":"/i/1174349?Store=16462\u0026Cate=26570",
                "couponId":"",
                "basketId":0,
                "cateNames":[
                    "民生日用",
                    "24H配送",
                    "衛生紙",
                    "炒鍋"
                ],
                "goodId":1174349,
                "cateId":26570,
                "amount":1,
                "colorId":"1137",
                "styleId":"1049",
                "gaCode":"",
                "parentSaleNo":null,
                "isJajago":false,
                "isGift":false,
                "isKit":false,
                "isKitItem":false,
                "giftNeedPickCount":0
            },
            {
                "itemId":"95e2822a-a59e-4f9a-9189-9bf7a70cc772",
                "productUrl":"/i/1174757",
                "couponId":"",
                "basketId":0,
                "cateNames":[

                ],
                "goodId":1174757,
                "cateId":0,
                "amount":1,
                "colorId":"0",
                "styleId":"0",
                "gaCode":"",
                "parentSaleNo":1174349,
                "isJajago":false,
                "isGift":true,
                "isKit":false,
                "isKitItem":false,
                "giftNeedPickCount":0
            },
            {
                "itemId":"aaf8e69c-a364-4e0d-a9fc-217715d052c2",
                "productUrl":"/i/1175130",
                "couponId":"",
                "basketId":0,
                "cateNames":[

                ],
                "goodId":1175130,
                "cateId":0,
                "amount":1,
                "colorId":"0",
                "styleId":"0",
                "gaCode":"",
                "parentSaleNo":1174349,
                "isJajago":false,
                "isGift":true,
                "isKit":false,
                "isKitItem":false,
                "giftNeedPickCount":0
            }
        ],
        "name":"滿額加價購-超取",
        "link":"/p/40229",
        "thresholdType":"Price",
        "thresholdValue":100
    },
    "Campaign_39949":{
        "groupId":"Campaign_39949",
        "groupKey":"39949",
        "groupType":"Campaign_M",
        "items":[
            {
                "itemId":"af69c764-7ab4-4b9c-8b9f-6fbf8f811abc",
                "productUrl":"/i/1173739?Store=16462\u0026Cate=26570",
                "couponId":"",
                "basketId":0,
                "cateNames":[
                    "民生日用",
                    "24H配送",
                    "衛生紙",
                    "炒鍋"
                ],
                "goodId":1173739,
                "cateId":26570,
                "amount":2,
                "colorId":"0",
                "styleId":"0",
                "gaCode":"",
                "parentSaleNo":null,
                "isJajago":false,
                "isGift":false,
                "isKit":false,
                "isKitItem":false,
                "giftNeedPickCount":0
            }
        ],
        "name":"滿額折-一般(定額)",
        "link":"/p/39949",
        "thresholdType":"Price",
        "thresholdValue":500
    },
    "Campaign_40172":{
        "groupId":"Campaign_40172",
        "groupKey":"40172",
        "groupType":"Campaign_P",
        "items":[
            {
                "itemId":"f546ba15-a1bd-4053-a787-dc0f4891b236",
                "productUrl":"/i/5004939?Store=16462\u0026Cate=26572",
                "couponId":"",
                "basketId":0,
                "cateNames":[
                    "民生日用",
                    "鍋具｜碗盤",
                    "各式鍋具  ",
                    "湯鍋 "
                ],
                "goodId":5004939,
                "cateId":26572,
                "amount":1,
                "colorId":"1019",
                "styleId":"1027",
                "gaCode":"",
                "parentSaleNo":null,
                "isJajago":false,
                "isGift":false,
                "isKit":false,
                "isKitItem":false,
                "giftNeedPickCount":0
            },
            {
                "itemId":"77ae79d3-b82d-413a-81ce-f82b1cd364b3",
                "productUrl":"/i/1173604?Store=126209\u0026Cate=35840",
                "couponId":"",
                "basketId":0,
                "cateNames":[
                    "數位／電玩／電競",
                    "手機",
                    "APPLE",
                    "iPhone 5c"
                ],
                "goodId":1173604,
                "cateId":35840,
                "amount":3,
                "colorId":"0",
                "styleId":"0",
                "gaCode":"",
                "parentSaleNo":null,
                "isJajago":false,
                "isGift":false,
                "isKit":false,
                "isKitItem":false,
                "giftNeedPickCount":0
            }
        ],
        "name":"m件n折-一般(定額)",
        "link":"/p/40172",
        "thresholdType":"Quantity",
        "thresholdValue":2
    },
    "Campaign_39968":{
        "groupId":"Campaign_39968",
        "groupKey":"39968",
        "groupType":"Campaign_GT",
        "items":[
            {
                "itemId":"ae67ff48-358a-40a2-88cb-8e048780828c",
                "productUrl":"/i/1174083?Store=16462\u0026Cate=26570",
                "couponId":"",
                "basketId":0,
                "cateNames":[
                    "民生日用",
                    "24H配送",
                    "衛生紙",
                    "炒鍋"
                ],
                "goodId":1174083,
                "cateId":26570,
                "amount":1,
                "colorId":"1137",
                "styleId":"1048",
                "gaCode":"",
                "parentSaleNo":null,
                "isJajago":false,
                "isGift":false,
                "isKit":false,
                "isKitItem":false,
                "giftNeedPickCount":0
            },
            {
                "itemId":"60b25d2c-8a14-46d2-aa1e-5ccfb60e050d",
                "productUrl":"/i/1172856?Store=6049\u0026Cate=28310",
                "couponId":"",
                "basketId":0,
                "cateNames":[
                    "內著塑衣",
                    "流行內衣褲",
                    "內衣款式",
                    "W鋼圈"
                ],
                "goodId":1172856,
                "cateId":28310,
                "amount":2,
                "colorId":"0",
                "styleId":"0",
                "gaCode":"",
                "parentSaleNo":null,
                "isJajago":false,
                "isGift":false,
                "isKit":false,
                "isKitItem":false,
                "giftNeedPickCount":0
            }
        ],
        "name":"滿額贈-一般",
        "link":"/p/39968",
        "thresholdType":"Price",
        "thresholdValue":3000
    },
    "Campaign_40222":{
        "groupId":"Campaign_40222",
        "groupKey":"40222",
        "groupType":"Campaign_GG",
        "items":[
            {
                "itemId":"a99b61f8-e2ca-4cb2-a5b5-53d606ac91c2",
                "productUrl":"/i/1174062?Store=16462\u0026Cate=26570",
                "couponId":"",
                "basketId":0,
                "cateNames":[
                    "民生日用",
                    "24H配送",
                    "衛生紙",
                    "炒鍋"
                ],
                "goodId":1174062,
                "cateId":26570,
                "amount":3,
                "colorId":"0",
                "styleId":"0",
                "gaCode":"",
                "parentSaleNo":null,
                "isJajago":false,
                "isGift":false,
                "isKit":false,
                "isKitItem":false,
                "giftNeedPickCount":0
            }
        ],
        "name":"滿額加價購-一般",
        "link":"/p/40222",
        "thresholdType":"Price",
        "thresholdValue":2000
    },
    "Campaign_40065":{
        "groupId":"Campaign_40065",
        "groupKey":"40065",
        "groupType":"Campaign_CA",
        "items":[
            {
                "itemId":"d8181eee-1bf8-4c63-aece-2a2574505350",
                "productUrl":"/i/1174572?Store=16462\u0026Cate=26570",
                "couponId":"",
                "basketId":0,
                "cateNames":[
                    "民生日用",
                    "24H配送",
                    "衛生紙",
                    "炒鍋"
                ],
                "goodId":1174572,
                "cateId":26570,
                "amount":2,
                "colorId":"0",
                "styleId":"0",
                "gaCode":"",
                "parentSaleNo":null,
                "isJajago":false,
                "isGift":false,
                "isKit":false,
                "isKitItem":false,
                "giftNeedPickCount":0
            },
            {
                "itemId":"0dfcc80d-9a98-4cf2-8887-4bee05a77a89",
                "productUrl":"/i/1174571?Store=16462\u0026Cate=26570",
                "couponId":"",
                "basketId":0,
                "cateNames":[
                    "民生日用",
                    "24H配送",
                    "衛生紙",
                    "炒鍋"
                ],
                "goodId":1174571,
                "cateId":26570,
                "amount":2,
                "colorId":"0",
                "styleId":"0",
                "gaCode":"",
                "parentSaleNo":null,
                "isJajago":false,
                "isGift":false,
                "isKit":false,
                "isKitItem":false,
                "giftNeedPickCount":0
            }
        ],
        "name":"任選 - 一般 (件數)",
        "link":"/p/40065",
        "thresholdType":"Quantity",
        "thresholdValue":2
    },
    "Campaign_40203":{
        "groupId":"Campaign_40203",
        "groupKey":"40203",
        "groupType":"Campaign_M",
        "items":[
            {
                "itemId":"e22eff86-e9c5-4ef0-b9e7-953fb917f136",
                "productUrl":"/i/1174597?Store=16462\u0026Cate=26570",
                "couponId":"",
                "basketId":0,
                "cateNames":[
                    "民生日用",
                    "24H配送",
                    "衛生紙",
                    "炒鍋"
                ],
                "goodId":1174597,
                "cateId":26570,
                "amount":1,
                "colorId":"0",
                "styleId":"1049",
                "gaCode":"mWeb_Home_HotRank_Product_全館_1174597_05",
                "parentSaleNo":null,
                "isJajago":false,
                "isGift":false,
                "isKit":false,
                "isKitItem":false,
                "giftNeedPickCount":0
            }
        ],
        "name":"滿額折-超商",
        "link":"/p/40203",
        "thresholdType":"Price",
        "thresholdValue":200
    },
    "Campaign_41277":{
        "groupId":"Campaign_41277",
        "groupKey":"41277",
        "groupType":"Campaign_M",
        "items":[
            {
                "itemId":"6b727527-284a-4b35-86fe-ba0a2c8a659b",
                "productUrl":"/i/1172490?Store=6049\u0026Cate=28310",
                "couponId":"",
                "basketId":0,
                "cateNames":[
                    "內著塑衣",
                    "流行內衣褲",
                    "內衣款式",
                    "W鋼圈"
                ],
                "goodId":1172490,
                "cateId":28310,
                "amount":1,
                "colorId":"1096",
                "styleId":"1128",
                "gaCode":"mWeb_Home_HotRank_Product_全館_1172490_09",
                "parentSaleNo":null,
                "isJajago":false,
                "isGift":false,
                "isKit":false,
                "isKitItem":false,
                "giftNeedPickCount":0
            }
        ],
        "name":"休閒test",
        "link":"/p/41277",
        "thresholdType":"Price",
        "thresholdValue":100
    }
}
